if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install()


BiocManager::install("biocLite") 
install.packages("genefilter")
install.packages("BiocManager")
install.packages("forcats")
install.packages("stringr")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("readr")
install.packages("tidyr")
install.packages("survminer")
install.packages("caret")
BiocManager::install("limma")
BiocManager::install("pheatmap")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("ArrayExpress")

BiocManager::install("GEOquery")

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("hgu133plus2.db")

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("impute")
BiocManager::install("caret")
BiocManager::install("hgu133plus2.db")
BiocManager::install("ExpressionAtlas")
install.packages("ExpressionAtlas")
install.packages("tidyverse")
install.packages("nnet")
install.packages("NeuralNetTools")
install.packages("h2o")
install.packages("dendextend")
install.packages("factoextra")
install.packages("clValid")
utils::install.packages("genefilter")
install.packages("genefilter", lib = "/usr/lib/R/library")
install.packages("BiocManager")
library("BiocManager")
BiocManager::install("genefilter")
install.packages("clusterCrit")
install.packages("plotcluster")

if (!require("BiocManager", quietly = TRUE)) 
  install.packages("BiocManager") # The following initializes usage of Bioc devel 
BiocManager::install(version='devel') 
BiocManager::install("genefilter")